require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MediaHistoriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # MediaHistory. As you add validations to MediaHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MediaHistoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all media_histories as @media_histories" do
      media_history = MediaHistory.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:media_histories)).to eq([media_history])
    end
  end

  describe "GET show" do
    it "assigns the requested media_history as @media_history" do
      media_history = MediaHistory.create! valid_attributes
      get :show, {:id => media_history.to_param}, valid_session
      expect(assigns(:media_history)).to eq(media_history)
    end
  end

  describe "GET new" do
    it "assigns a new media_history as @media_history" do
      get :new, {}, valid_session
      expect(assigns(:media_history)).to be_a_new(MediaHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested media_history as @media_history" do
      media_history = MediaHistory.create! valid_attributes
      get :edit, {:id => media_history.to_param}, valid_session
      expect(assigns(:media_history)).to eq(media_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MediaHistory" do
        expect {
          post :create, {:media_history => valid_attributes}, valid_session
        }.to change(MediaHistory, :count).by(1)
      end

      it "assigns a newly created media_history as @media_history" do
        post :create, {:media_history => valid_attributes}, valid_session
        expect(assigns(:media_history)).to be_a(MediaHistory)
        expect(assigns(:media_history)).to be_persisted
      end

      it "redirects to the created media_history" do
        post :create, {:media_history => valid_attributes}, valid_session
        expect(response).to redirect_to(MediaHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved media_history as @media_history" do
        post :create, {:media_history => invalid_attributes}, valid_session
        expect(assigns(:media_history)).to be_a_new(MediaHistory)
      end

      it "re-renders the 'new' template" do
        post :create, {:media_history => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested media_history" do
        media_history = MediaHistory.create! valid_attributes
        put :update, {:id => media_history.to_param, :media_history => new_attributes}, valid_session
        media_history.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested media_history as @media_history" do
        media_history = MediaHistory.create! valid_attributes
        put :update, {:id => media_history.to_param, :media_history => valid_attributes}, valid_session
        expect(assigns(:media_history)).to eq(media_history)
      end

      it "redirects to the media_history" do
        media_history = MediaHistory.create! valid_attributes
        put :update, {:id => media_history.to_param, :media_history => valid_attributes}, valid_session
        expect(response).to redirect_to(media_history)
      end
    end

    describe "with invalid params" do
      it "assigns the media_history as @media_history" do
        media_history = MediaHistory.create! valid_attributes
        put :update, {:id => media_history.to_param, :media_history => invalid_attributes}, valid_session
        expect(assigns(:media_history)).to eq(media_history)
      end

      it "re-renders the 'edit' template" do
        media_history = MediaHistory.create! valid_attributes
        put :update, {:id => media_history.to_param, :media_history => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested media_history" do
      media_history = MediaHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => media_history.to_param}, valid_session
      }.to change(MediaHistory, :count).by(-1)
    end

    it "redirects to the media_histories list" do
      media_history = MediaHistory.create! valid_attributes
      delete :destroy, {:id => media_history.to_param}, valid_session
      expect(response).to redirect_to(media_histories_url)
    end
  end

end
